dist: xenial
sudo: false
language: python
cache: pip

script:
  - tox

install:
  - pip install tox tox-travis

matrix:
  include:
    - python: "2.7"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"

    - python: "pypy2.7-6.0"
    - python: "pypy3.5-6.0"

    # Documentation
    - python: "3.7"
      env: TOXENV=docs
    - python: "3.7"
      env: TOXENV=linkcheck

    # Linting
    - python: "3.7"
      env: TOXENV=examples
    - python: "3.7"
      env: TOXENV=lint

services:
  - mongodb

notifications:
  email: false
  irc: "irc.freenode.org#factory_boy"
