sudo: false
language: python
cache: pip

script:
  - tox

install:
  - pip install tox

matrix:
  include:
    # Django 1.11
    - python: "2.7"
      env: TOXENV=py27-django111-alchemy12-mongoengine015
    - python: "3.4"
      env: TOXENV=py34-django111-alchemy12-mongoengine015
    - python: "3.5"
      env: TOXENV=py35-django111-alchemy12-mongoengine015
    - python: "3.6"
      env: TOXENV=py36-django111-alchemy12-mongoengine015

    # Django 2.0
    - python: "3.4"
      env: TOXENV=py34-django20-alchemy12-mongoengine015
    - python: "3.5"
      env: TOXENV=py35-django20-alchemy12-mongoengine015
    - python: "3.6"
      env: TOXENV=py36-django20-alchemy12-mongoengine015
    - python: "3.7"
      env: TOXENV=py37-django20-alchemy12-mongoengine015
      dist: xenial
      sudo: true

    # Django 2.1
    - python: "3.5"
      env: TOXENV=py35-django21-alchemy12-mongoengine015
    - python: "3.6"
      env: TOXENV=py36-django21-alchemy12-mongoengine015
    - python: "3.7"
      env: TOXENV=py37-django21-alchemy12-mongoengine015
      dist: xenial
      sudo: true

    # Pypy
    - python: "pypy"
      env: TOXENV=pypy-django111-alchemy12-mongoengine015
    - python: "pypy3"
      env: TOXENV=pypy3-django20-alchemy12-mongoengine015

    # Django 2.0
    - python: "nightly"
      env: TOXENV=pynightly-django20-alchemy12-mongoengine015
      dist: xenial
      sudo: true
    # Django 2.1
    - python: "nightly"
      env: TOXENV=pynightly-django21-alchemy12-mongoengine015
      dist: xenial
      sudo: true

    # Documentation
    - python: 3.6
      env: TOXENV=linkcheck

    # Linting
    - python: "3.7"
      env: TOXENV=examples
      dist: xenial
      sudo: true
    - python: "3.7"
      env: TOXENV=lint
      dist: xenial
      sudo: true
  allow_failures:
    # Django 2.0
    - python: "nightly"
      env: TOXENV=pynightly-django20-alchemy12-mongoengine015
      dist: xenial
      sudo: true
    # Django 2.1
    - python: "nightly"
      env: TOXENV=pynightly-django21-alchemy12-mongoengine015
      dist: xenial
      sudo: true

services:
  - mongodb

notifications:
  email: false
  irc: "irc.freenode.org#factory_boy"
