language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

script:
  - python setup.py test

install:
  - if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pip install unittest2 --use-mirrors; fi
  - pip install Django sqlalchemy --use-mirrors
  - if ! python --version 2>&1 | grep -q -i pypy ; then pip install Pillow --use-mirrors; fi

notifications:
  email: false
  irc: "irc.freenode.org#factory_boy"
